name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          if [ -f "Numeric Methods/Newton–Raphson/requirements.txt" ]; then
            pip install -r "Numeric Methods/Newton–Raphson/requirements.txt"
          else
            pip install pytest sympy numpy scipy
          fi

      - name: Run tests (Newton–Raphson subproject)
        run: |
          pytest -q "Numeric Methods/Newton–Raphson"
